### ISSUE TITLE
Path ignore filter may not work as expected

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/.github#124]
We noticed in text that in pull requests where both javascript and php files are changed, the paths-ignore filter is not working as expected.

https://github.com/nextcloud/text/blob/main/.github/workflows/node-when-unrelated.yml#L13C7-L22

The reason is that the workflow will only be skippped if all paths match:

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-paths

> When all the path names match patterns in paths-ignore, the workflow will not run. If any path names do not match patterns in paths-ignore, even if some path names match the patterns, the workflow will run.

This has caused the branch protection to still pass as the node-when-unrelated.ymnl check succeeded while the node.yml check was canceled due to the same name of the concurrency group.

I don't see a way to make this work with the limited github actions syntax, so maybe https://github.com/getsentry/paths-filter could be a different option.

Did anyone else encounter this as well?

cc @nickvergessen as you worked on those fallback checks.

## Affected run/PR

https://github.com/nextcloud/text/pull/2971
https://github.com/nextcloud/text/actions/runs/4052668917
https://github.com/nextcloud/text/actions/runs/4052668905

**Comment by nickvergessen** [comment]
Ah, yeah I saw it flying by somewhere, but didn't came to the debugging phase yet.

> I don't see a way to make this work with the limited github actions syntax, so maybe https://github.com/getsentry/paths-filter could be a different option.

Yeah seems like it.

**Comment by susnux** [comment]
Fixed by @nickvergessen in https://github.com/nextcloud/.github/commit/b7e53a6ab3ca3d8445ae9b8ee65fa7a75fb0cff2
