### ISSUE TITLE
Nextcloud 25.0.3 |  Duedate or any tag setup not shown in all activity/timeline For Deck 

### ISSUE THREAD

**Issue by digitalteamgkdi** [nextcloud/.github#180]
I'd like to ask. is there a way to find out the date of determining a due date on the card in the deck.
Due date determination activities are not recorded in the activities menu or timeline.

Likewise for labeling activities, they are not listed on the timeline or activities menu.

has anyone experienced this. Please help. Thank You.

![image](https://github.com/nextcloud/.github/assets/122334644/3d1cd1ed-c6dc-429c-a9e0-8e2c4231a686)
![Screenshot 2023-06-19 160645](https://github.com/nextcloud/.github/assets/122334644/742bddf3-f55e-40d2-9542-9d5f79dff77c)

I hope it can be like other management tools that can record all the activities that we apply to a card. like below.
![image](https://github.com/nextcloud/.github/assets/122334644/be9fef4d-6392-4944-9330-7776dee45f99)

**Comment by juliushaertl** [comment]
Please head over to https://github.com/nextcloud/deck/issues and also use the search to see if a similar issue already exists.
