### ISSUE TITLE
Github action can not release/package if 23 is the lowest version allowed

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/.github#23]
Ref https://github.com/nextcloud-releases/external/runs/4154359414?check_suite_focus=true

> ### Checkout server 23
> Run NCVERSION=23
>   NCVERSION=23
>   wget --quiet https://download.nextcloud.com/server/releases/latest-$NCVERSION.zip
>   unzip latest-$NCVERSION.zip
>   shell: /usr/bin/bash -e {0}
>   env:
>     PHP_VERSION: 7.4
>     APP_NAME: external
>     APP_VERSION: v3.10.1
> Error: Process completed with exit code 8.

We will run into this issue basically every release when app devs try to outsmart the time schedule and need to prepare many releases.

We could start something like `latest-` on the prereleases (https://download.nextcloud.com/server/prereleases/ has packages for 23) and then try downloading from there as a second option?

**Comment by nickvergessen** [comment]
actually also RCs are in prereleases, so this should be fixed one way or another

**Comment by skjnldsv** [comment]
AH damn, I haven't thought about apps that only support master and above :thinking:

**Comment by skjnldsv** [comment]
I guess we can fallback on checking master out
