### ISSUE TITLE
Create default community health files

### ISSUE THREAD

**Issue by tcitworld** [nextcloud/.github#31]
Put the CONTRIBUTING.md and SECURITY.md files from server here and they will be automatically applied to all of the `nextcloud/` repositories.

Ref https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file#about-default-community-health-files

**Comment by ChristophWurst** [comment]
I'd say we move those two server files into this repo if github picks it up as it it was in its old location. Copying makes it more prone to getting out of sync.

cc @AndyScherzinger @juliushaertl @nickvergessen @skjnldsv because it's a change effecting all repos that don't have their own CONTRIBUTING/SECURITY files

**Comment by skjnldsv** [comment]
All good from me!

**Comment by AndyScherzinger** [comment]
All good for me, while we then need to have a generic one for both because if I check Android Files just as an example than there are also a lot of Android specifics in it, so the files here should then be coarse grained enough to work for clients, server, apps, libs, etc.

**Comment by tcitworld** [comment]
@AndyScherzinger These are only default ones, very generic indeed, if there's some specific ones in a repo they will take precedence.

> If a repository has any files in its own .github/ISSUE_TEMPLATE folder, including issue templates or a config.yml file, none of the contents of the default .github/ISSUE_TEMPLATE folder will be used.

**Comment by AndyScherzinger** [comment]
@tcitworld perfect! 💙
