### ISSUE TITLE
Need help with dependabot automerge

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/.github#74]
It always fails for me with the bookmarks app: [[nextcloud-command](https://github.com/nextcloud-command)](https://github.com/nextcloud/bookmarks/pull/1851)

**Comment by juliushaertl** [comment]
Might be due to the branch protection setting "Restrict who can push to matching branches". Maybe you can add the bot there.

**Comment by marcelklehr** [comment]
Ah, I had added nextcloud-bot, but not nextcloud-command, let's see if it works now

**Comment by marcelklehr** [comment]
mh, still doesn't work: https://github.com/nextcloud/bookmarks/pull/1861

**Comment by skjnldsv** [comment]
> Ah, I had added nextcloud-bot, but not nextcloud-command, let's see if it works now

Don't add nextcloud-command, I removed it.
I see you were having [an update of the workflow pending](https://github.com/nextcloud/bookmarks/pull/1859), I merged it and rebased the vimeo update PR

**Comment by skjnldsv** [comment]
![image](https://user-images.githubusercontent.com/14975046/183285084-8b9483b3-8a78-437d-ab8e-4ce7d7d28997.png)

This is your issue, you need to allow dependabot, but it's an app not a user

**Comment by skjnldsv** [comment]
Removed the protection, we don't use that anywhere else

**Comment by marcelklehr** [comment]
Thank you :tada:
